# Generated by Django 3.2.4 on 2021-06-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultdata',
            name='senior',
        ),
    ]
