# Generated by Django 3.2.4 on 2021-06-27 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_facultdata_senior'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultdata',
            name='CCurTeach',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='facultdata',
            name='CourTaught',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='facultdata',
            name='CurRes',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='facultdata',
            name='Dept',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='facultdata',
            name='Designation',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='facultdata',
            name='Experience',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='facultdata',
            name='ProfMem',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='facultdata',
            name='Pub',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='facultdata',
            name='ResInt',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='facultdata',
            name='chairman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultdata',
            name='email',
            field=models.EmailField(default='NA', max_length=254),
        ),
        migrations.AddField(
            model_name='facultdata',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultdata',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultdata',
            name='qual',
            field=models.TextField(default='NA'),
        ),
    ]
